const screens={song:document.getElementById("songScreen"),quiz:document.getElementById("quizScreen"),result:document.getElementById("resultScreen")};
const els={startBtn:document.getElementById("startBtn"),loopBtn:document.getElementById("loopBtn"),nextBtn:document.getElementById("nextBtn"),stageLabel:document.getElementById("stageLabel"),scoreLabel:document.getElementById("scoreLabel"),questionMeta:document.getElementById("questionMeta"),questionText:document.getElementById("questionText"),answerArea:document.getElementById("answerArea"),feedback:document.getElementById("feedback"),meterFill:document.getElementById("meterFill"),resultTitle:document.getElementById("resultTitle"),resultText:document.getElementById("resultText"),finalScore:document.getElementById("finalScore"),finalRate:document.getElementById("finalRate"),songVideo:document.getElementById("songVideo"),videoFallback:document.getElementById("videoFallback")};
const choiceQuestions=[{prompt:"市町村が指定するサービスに入るものはどれ？",options:["地域密着型","介護老人福祉施設","訪問看護"],answer:"地域密着型",note:"市町村指定は、地域密着型・居宅介護支援・介護予防支援の3つです。"},{prompt:"市町村指定の3つに含まれる「ケアプラン」系のサービスは？",options:["居宅介護支援","短期入所生活介護","通所介護"],answer:"居宅介護支援",note:"居宅介護支援は市町村指定です。"},{prompt:"市町村指定の3つに含まれる予防系サービスは？",options:["介護予防支援","介護予防訪問看護","介護予防通所リハビリ"],answer:"介護予防支援",note:"介護予防支援も、市町村指定の3つのひとつです。"},{prompt:"地域密着型・居宅介護支援・介護予防支援以外は、原則だれが指定する？",options:["都道府県知事","厚生労働大臣","市町村長"],answer:"都道府県知事",note:"3つ以外は都道府県知事、と押さえます。"},{prompt:"「地域」と「ケアプラン」は身近だから、指定するのは？",options:["市町村","都道府県","国"],answer:"市町村",note:"覚え歌の合言葉は「身近だから市町村」です。"},{prompt:"市町村の仕事に含まれるものは？",options:["指定・6年更新・指導監督","年金額の決定","医師免許の発行"],answer:"指定・6年更新・指導監督",note:"指定、6年更新、指導監督は市町村の仕事です。"},{prompt:"介護保険施設を指定するのは？",options:["都道府県知事","市町村","利用者代表"],answer:"都道府県知事",note:"介護保険施設は都道府県知事が指定します。"}];
const trueFalseQuestions=[{prompt:"市町村指定は、地域密着型・居宅介護支援・介護予防支援の3つだけである。",answer:true,note:"その通り。まずはこの3つを固定します。"},{prompt:"地域密着型サービスは、都道府県知事が指定する。",answer:false,note:"地域密着型は市町村指定です。"},{prompt:"人員、設備、運営の基準設定は、市町村の仕事に含まれる。",answer:true,note:"基準設定は市町村の仕事のひとつです。"},{prompt:"報告命令・立入検査は、市町村の仕事に含まれない。",answer:false,note:"報告命令・立入検査は市町村の仕事です。"},{prompt:"施設指定時の意見提出は、市町村の仕事に含まれる。",answer:true,note:"施設指定時には市町村が意見提出できます。"},{prompt:"介護保険施設は、市町村が指定する。",answer:false,note:"介護保険施設は都道府県知事が指定します。"},{prompt:"定期巡回不足時の協議要求は、市町村の仕事に含まれる。",answer:true,note:"定期巡回不足時の協議要求も押さえどころです。"}];
const blankQuestion={prompt:"穴埋めで仕上げ",lines:[{label:"市町村指定 1",answer:"地域密着型"},{label:"市町村指定 2",answer:"居宅介護支援"},{label:"市町村指定 3",answer:"介護予防支援"},{label:"それ以外の指定者",answer:"都道府県知事"},{label:"更新期間",answer:"6年"}],note:"地域密着型・居宅介護支援・介護予防支援、それ以外は都道府県知事、更新は6年です。"};
const questions=[...choiceQuestions.map(q=>({...q,type:"choice",stage:"3択問題"})),...trueFalseQuestions.map(q=>({...q,type:"tf",stage:"〇×問題"})),{...blankQuestion,type:"blank",stage:"穴埋め問題"}];
let current=0,score=0,answered=false;
function showScreen(name){Object.values(screens).forEach(screen=>screen.classList.remove("active"));screens[name].classList.add("active")}
function normalizeText(value){return value.trim().replace(/\s+/g,"").replace(/[０-９]/g,char=>String.fromCharCode(char.charCodeAt(0)-0xfee0)).replace(/ヶ/g,"ケ")}
function setScoreLabel(){els.scoreLabel.textContent=score+" / "+questions.length}
function startQuiz(){current=0;score=0;answered=false;setScoreLabel();showScreen("quiz");renderQuestion()}
function renderQuestion(){const q=questions[current];answered=false;els.stageLabel.textContent=q.stage;els.questionMeta.textContent=q.stage+" "+(current+1)+" / "+questions.length;els.questionText.textContent=q.prompt;els.answerArea.innerHTML="";els.answerArea.classList.remove("tf-grid");els.feedback.textContent="";els.feedback.className="feedback";els.nextBtn.classList.add("hidden");els.meterFill.style.width=(current/questions.length*100)+"%";if(q.type==="choice")renderChoices(q);if(q.type==="tf")renderTrueFalse(q);if(q.type==="blank")renderBlanks(q)}
function renderChoices(q){q.options.forEach(option=>{const button=document.createElement("button");button.className="answer-btn";button.textContent=option;button.addEventListener("click",()=>gradeSingle(button,option===q.answer,q));els.answerArea.append(button)})}
function renderTrueFalse(q){els.answerArea.classList.add("tf-grid");[{label:"〇",value:true},{label:"×",value:false}].forEach(item=>{const button=document.createElement("button");button.className="answer-btn";button.textContent=item.label;button.setAttribute("aria-label",item.value?"正しい":"誤り");button.addEventListener("click",()=>gradeSingle(button,item.value===q.answer,q));els.answerArea.append(button)})}
function renderBlanks(q){const form=document.createElement("form");form.className="blank-form";q.lines.forEach((line,index)=>{const wrap=document.createElement("div");wrap.className="blank-line";const label=document.createElement("label");label.textContent=line.label;label.setAttribute("for","blank-"+index);const input=document.createElement("input");input.id="blank-"+index;input.className="blank-input";input.autocomplete="off";input.inputMode=index===4?"numeric":"text";wrap.append(label,input);form.append(wrap)});const button=document.createElement("button");button.className="primary";button.type="submit";button.textContent="答え合わせ";form.append(button);form.addEventListener("submit",event=>{event.preventDefault();if(answered)return;const inputs=[...form.querySelectorAll("input")];const correctCount=inputs.reduce((count,input,index)=>{const ok=normalizeText(input.value)===normalizeText(q.lines[index].answer);input.style.borderColor=ok?"rgba(22,132,86,.7)":"rgba(209,67,67,.7)";return count+Number(ok)},0);const isPerfect=correctCount===q.lines.length;score+=Number(isPerfect);answered=true;setScoreLabel();els.feedback.textContent=isPerfect?"正解！ "+q.note:correctCount+"/"+q.lines.length+" 個正解。答え："+q.lines.map(line=>line.answer).join("・");els.feedback.classList.add(isPerfect?"good":"bad");els.nextBtn.classList.remove("hidden")});els.answerArea.append(form)}
function gradeSingle(button,isCorrect,q){if(answered)return;answered=true;score+=Number(isCorrect);setScoreLabel();[...els.answerArea.querySelectorAll(".answer-btn")].forEach(btn=>{btn.disabled=true;if(btn.textContent===q.answer||(q.type==="tf"&&((btn.textContent==="〇")===q.answer)))btn.classList.add("correct")});if(!isCorrect)button.classList.add("wrong");els.feedback.textContent=(isCorrect?"正解！":"惜しい！")+" "+q.note;els.feedback.classList.add(isCorrect?"good":"bad");els.nextBtn.classList.remove("hidden")}
function nextQuestion(){current+=1;if(current>=questions.length)return showResult();renderQuestion()}
function showResult(){const rate=Math.round(score/questions.length*100);els.stageLabel.textContent="結果発表";els.finalScore.textContent=score+" / "+questions.length;els.finalRate.textContent=rate+"%";if(rate>=90){els.resultTitle.textContent="かなり仕上がっています";els.resultText.textContent="市町村指定の3つと市町村の仕事がきれいに入っています。"}else if(rate>=65){els.resultTitle.textContent="あと少しで安定";els.resultText.textContent="迷ったところだけ、覚え歌に戻ってもう一周しましょう。"}else{els.resultTitle.textContent="歌に戻って再チャレンジ";els.resultText.textContent="まずは「地域」と「ケアプラン」は身近だから市町村、から固めましょう。"}showScreen("result")}
function returnToSong(){els.stageLabel.textContent="覚え歌";showScreen("song");els.songVideo.currentTime=0;els.songVideo.play().catch(()=>{})}
els.startBtn.addEventListener("click",startQuiz);els.nextBtn.addEventListener("click",nextQuestion);els.loopBtn.addEventListener("click",returnToSong);els.songVideo.addEventListener("error",()=>els.videoFallback.classList.remove("hidden"));setScoreLabel();